#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2006 (ita)

# notes:
# 1. We think it is good to give names to our objects
# 2. In practice something like 'libkdegames' might do it better
# 3. Any coincidence with characters living or dead is purely coincidental

def build(bld):
	import Options
	# Add example compilation
	bld.new_task_gen(
		features = 'cxx cprogram',
		source = 'example.cpp SimpleController.cpp BasicFileInput.cpp TestingHarness.cpp Schema.cpp',
		includes = '. include /usr/include',
		uselib = 'LEONARD ALLEGRO',
		target = 'leonardexample')

def set_options(opt):
	# options defined if src/ was to be compiled as a standalone module
	#opt.add_option('--meow', type='string', help='option hidden in the src module', dest='meow')
	pass
def configure(conf):
	print "sub-configuration file called (demo)"

